name: Update Jadwal Wayang

on:
workflow_dispatch:
schedule:
- cron: "0 */3 * * *"

jobs:
update:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      token: ${{ secrets.GITHUB_TOKEN }}

  - name: Fetch RSS
    run: |
      curl -L https://www.kluban.net/feeds/posts/default?alt=json -o rss.json

  - name: Commit & Push
    run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"
      git add rss.json
      git commit -m "Auto update RSS" || echo "No changes"
      git push
